version: "2"
services:
    maven:
      build:
       context: ./maven
      volumes:
       - l7:/boxfuse-sample-java-war-hello/

    tomcat:
#      image: tomcat
      build:
       context: ./tomcat      
      depends_on:
       - maven
      ports:
       - "80:8080"
      volumes:
       - l7:/usr/local/tomcat/bin

volumes: 
    l7: