version: "3.4"
  services:

    maven:
      build:
       context: ./maven
      volumes:
       - l7:/volume1
  
    tomcat:
      image: tomcat:latest
      ports:
        - "80:8080"
      volumes:
       - l7:/var/lib/tomcat/webapps/

  volumes: 
    l7: