version: "2"
services:
    maven:
      build:
       context: ./maven
      volumes:
       - l7:/volume1
    tomcat:
#      image: tomcat
      build:
       context: ./tomcat      
      depends_on:
       - maven
      ports:
       - "80:8080"
      volumes:
       - l7:/var/lib/tomcat/webapps/

volumes: 
    l7: